image_process:
  gaussian_blur_sigma: 1.0
  empty_image_threshold: 253
  retry_args:
    - binarization_threshold: 172
      erode_kernel: 1
      morphology_kernel: 5
    - binarization_threshold: 172
      erode_kernel: 2
      morphology_kernel: 5
    - binarization_threshold: 172
      erode_kernel: 2
      morphology_kernel: 6
    - binarization_threshold: 172
      erode_kernel: 3
      morphology_kernel: 6
    - binarization_threshold: 172
      erode_kernel: 0
      morphology_kernel: 5
image_baizheng:
  page_number_diff: 0.146
  model_points_3_angle_threshold: 1.046
  model_point_wh_cosine_similarity: 0.985
  model_point_min_wh: 10
  model_point_max_wh: 70
  model_point_diff: 45
  model_point_scan_range: 6
  assist_point_scan_range: 8
  assist_point_min_distance: 6
  assist_point_max_distance: 25
  model_point_min_distance: 6
  model_point_max_distance: 60
  assist_point_nearby_length: 4
  valid_coordinates4_cosine_similarity: 0.996
  valid_coordinates_wh_sum_mean_dis: 8.0
image_blackfill:
  neighborhood_size: 5
  image_type: 0
  min_filled_ratio: 0.5
recognize_type:
  black_fill: 1
  vx: 2
  number: 3
  qrcode: 4
  barcode: 5
  coordinate: 6