image_process:
  gaussian_blur_sigma: 1.0
  binarization_threshold: 180
  morphology_kernel: 5
  empty_image_threshold: 253
image_baizheng:
  page_number_diff: 0.21
  model_point_wh_cosine_similarity: 0.985
  model_point_diff: 50
  model_point_scan_range: 6
  assist_point_scan_range: 4
image_blackfill:
  image_type: 0
  min_filled_ratio: 0.5
recognize_type:
  black_fill: 1
  vx: 2
  number: 3
  qrcode: 4
  barcode: 5
  coordinate: 6

  
