/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function initialize(inputJson: string): void
export function inference(inputJson: string): string
export function inferenceSecond(inputJson: string): string
